### ISSUE TITLE
Lud-18 specification questions

### ISSUE THREAD

**Issue by michaelWuensch** [btcontract/lnurl-rfc#109]
In lud-18 there is no description at all how this should be handled on the wallet in regards to UX.
Is the wallet required to notify the user that it sends the pubkey as identity or does it do it without the users knowledge?
Does the user have to input email, identifier and a text, if SERVICE has all of these 3 identities as mandatory?
Does the wallet have to make sure valid data is inputted in email and identifier field?

Further more I have to admit that I don't really see a usecase for those loose identification methods. 
Email, identifier, text and pubkey do not proof anything. The only method that proofs a identity is the "auth" method.
Do you have a specific example where the loose identification methods are needed or already used and why?

Implementing the UI for those loose methods in a wallet is quite a lot of work as it involves extra input fields

**Comment by fiatjaf** [comment]
In my mind the idea is that wallets implement what make sense for them. Email, for example, makes no sense to me in any situation ever.

It doesn't make much sense to have the inputs for those loose identifiers in mobile wallets, I agree, and it's totally fine to not implement. They make more sense when it's a custodial wallet with named accounts paying to another (using Lightning Addresses, LUD-16), or to a service that deals well with loose names like https://chat.blixtwallet.com/.

On the other hand @hsjoberg's (mobile noncustodial) wallet Blixt has had a field for a loose user name since before LNURL existed I think, so that fits well, the user doesn't have to type a name every time, they just set their name once and are done with it.

If a service is requesting mandatory stuff the wallet doesn't implement wallet should fail with an error like "service is mandating fields x, y and z, which we can't provide". But that's just my opinion. I don't think the spec should dictate wallet behavior.

Also I don't think the spec should dictate that wallets validate input fields, because the service must validate these on their own anyway if they want to do something useful with them. Wallets can decide to validate or not, depending on how they choose to implement each thing and how they think it's the best user experience.

**Comment by fiatjaf** [comment]
If you think this is good, we can add a "recommendations" section containing stuff like "wallet should show an error if services is requiring a field it can't provide" and so on. But I don't think any of that should be dictated.

**Comment by hsjoberg** [comment]
> Email, identifier, text and pubkey do not proof anything

LUD-18 title was changed from "proof of payer" to "payer identity" for this reason.
But I don't believe that just because you cannot prove something, it wouldn't be useful...

>  Do you have a specific example where the loose identification methods are needed or already used and why?

Yes, for things like Lightning Address, it would provide useful information to see by whom you were paid. Now the identity is not proven of course, but this could be further extended, let's take things in steps.

**Comment by michaelWuensch** [comment]
Ah, yes in combination with lightning address this might really be useful. Thanks for your answers guys!
