### ISSUE TITLE
lud-16: User not found handling

### ISSUE THREAD

**Issue by michaelWuensch** [btcontract/lnurl-rfc#111]
Hi,
while implementing lud-16 I noticed that ln.tips and lntxbot.com both return a valid response no matter what name you input there.
zbd.gg returns an error stating "User not found".

My PR (#105 ) where it says that it should throw an error in the first json response was merged after those services implemented it.
ln.tips failed later when actually trying to make the payment.
But when sending 100 sats to a completely random lntxbot.com address the payment went through.
What do you think, should we contact them to change the behavior?

**Comment by michaelWuensch** [comment]
Or would it make sense to remove that requirement again? Maybe you can send funds there and the user of that service can claim it anytime if he wants to.

**Comment by fiatjaf** [comment]
I think we should contact them and let them know about it, because it's probably a bug (this is a joke, it's me, I always forget to fix that).

But I also think that paragraph should be removed, in my opinion that bit about returning an error or not -- or making the funds available for users at a later date -- should be left by the service owner to choose.

Also, LUD-16 addresses may not even be directly related to _users_, they could represent specific services or goods that are being sold, like https://lnurl-pay.me/ does, for example.

**Comment by michaelWuensch** [comment]
Ok, then lets remove it again. :)
